// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductLogService.proto

package com.alvin.logservice.lib.product;

/**
 * Protobuf type {@code com.alvin.logservice.lib.product.ProductLogReply}
 */
public  final class ProductLogReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.alvin.logservice.lib.product.ProductLogReply)
    ProductLogReplyOrBuilder {
  // Use ProductLogReply.newBuilder() to construct.
  private ProductLogReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductLogReply() {
    done_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ProductLogReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            done_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.alvin.logservice.lib.product.ProductLogServiceOuter.internal_static_com_alvin_logservice_lib_product_ProductLogReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.alvin.logservice.lib.product.ProductLogServiceOuter.internal_static_com_alvin_logservice_lib_product_ProductLogReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.alvin.logservice.lib.product.ProductLogReply.class, com.alvin.logservice.lib.product.ProductLogReply.Builder.class);
  }

  public static final int DONE_FIELD_NUMBER = 1;
  private boolean done_;
  /**
   * <code>bool done = 1;</code>
   */
  public boolean getDone() {
    return done_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (done_ != false) {
      output.writeBool(1, done_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (done_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, done_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.alvin.logservice.lib.product.ProductLogReply)) {
      return super.equals(obj);
    }
    com.alvin.logservice.lib.product.ProductLogReply other = (com.alvin.logservice.lib.product.ProductLogReply) obj;

    boolean result = true;
    result = result && (getDone()
        == other.getDone());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DONE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDone());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.alvin.logservice.lib.product.ProductLogReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.alvin.logservice.lib.product.ProductLogReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.alvin.logservice.lib.product.ProductLogReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.alvin.logservice.lib.product.ProductLogReply)
      com.alvin.logservice.lib.product.ProductLogReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alvin.logservice.lib.product.ProductLogServiceOuter.internal_static_com_alvin_logservice_lib_product_ProductLogReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alvin.logservice.lib.product.ProductLogServiceOuter.internal_static_com_alvin_logservice_lib_product_ProductLogReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alvin.logservice.lib.product.ProductLogReply.class, com.alvin.logservice.lib.product.ProductLogReply.Builder.class);
    }

    // Construct using com.alvin.logservice.lib.product.ProductLogReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      done_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.alvin.logservice.lib.product.ProductLogServiceOuter.internal_static_com_alvin_logservice_lib_product_ProductLogReply_descriptor;
    }

    public com.alvin.logservice.lib.product.ProductLogReply getDefaultInstanceForType() {
      return com.alvin.logservice.lib.product.ProductLogReply.getDefaultInstance();
    }

    public com.alvin.logservice.lib.product.ProductLogReply build() {
      com.alvin.logservice.lib.product.ProductLogReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.alvin.logservice.lib.product.ProductLogReply buildPartial() {
      com.alvin.logservice.lib.product.ProductLogReply result = new com.alvin.logservice.lib.product.ProductLogReply(this);
      result.done_ = done_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.alvin.logservice.lib.product.ProductLogReply) {
        return mergeFrom((com.alvin.logservice.lib.product.ProductLogReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.alvin.logservice.lib.product.ProductLogReply other) {
      if (other == com.alvin.logservice.lib.product.ProductLogReply.getDefaultInstance()) return this;
      if (other.getDone() != false) {
        setDone(other.getDone());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.alvin.logservice.lib.product.ProductLogReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.alvin.logservice.lib.product.ProductLogReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean done_ ;
    /**
     * <code>bool done = 1;</code>
     */
    public boolean getDone() {
      return done_;
    }
    /**
     * <code>bool done = 1;</code>
     */
    public Builder setDone(boolean value) {
      
      done_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool done = 1;</code>
     */
    public Builder clearDone() {
      
      done_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.alvin.logservice.lib.product.ProductLogReply)
  }

  // @@protoc_insertion_point(class_scope:com.alvin.logservice.lib.product.ProductLogReply)
  private static final com.alvin.logservice.lib.product.ProductLogReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.alvin.logservice.lib.product.ProductLogReply();
  }

  public static com.alvin.logservice.lib.product.ProductLogReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductLogReply>
      PARSER = new com.google.protobuf.AbstractParser<ProductLogReply>() {
    public ProductLogReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProductLogReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductLogReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductLogReply> getParserForType() {
    return PARSER;
  }

  public com.alvin.logservice.lib.product.ProductLogReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

