// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductLogService.proto

package com.alvin.logservice.lib.product;

public interface ProductLogReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alvin.logservice.lib.product.ProductLogReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool done = 1;</code>
   */
  boolean getDone();
}
