// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductLogService.proto

package com.alvin.logservice.lib.product;

public final class ProductLogServiceOuter {
  private ProductLogServiceOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alvin_logservice_lib_product_ProductLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alvin_logservice_lib_product_ProductLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alvin_logservice_lib_product_ProductLogReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alvin_logservice_lib_product_ProductLogReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ProductLogService.proto\022 com.alvin.log" +
      "service.lib.product\"\332\001\n\021ProductLogReques" +
      "t\022\017\n\007orderId\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\r\n\005l" +
      "ogAt\030\003 \001(\003\022K\n\006opType\030\004 \001(\0162;.com.alvin.l" +
      "ogservice.lib.product.ProductLogRequest." +
      "OPTypes\"G\n\007OPTypes\022\013\n\007CREATED\020\000\022\010\n\004EDIT\020" +
      "\001\022\013\n\007INBOUND\020\002\022\014\n\010OUTBOUND\020\003\022\n\n\006DELETE\020\004" +
      "\"\037\n\017ProductLogReply\022\014\n\004done\030\001 \001(\0102\210\001\n\021Pr" +
      "oductLogService\022s\n\007saveLog\0223.com.alvin.l" +
      "ogservice.lib.product.ProductLogRequest\032",
      "1.com.alvin.logservice.lib.product.Produ" +
      "ctLogReply\"\000B<\n com.alvin.logservice.lib" +
      ".productB\026ProductLogServiceOuterP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alvin_logservice_lib_product_ProductLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alvin_logservice_lib_product_ProductLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alvin_logservice_lib_product_ProductLogRequest_descriptor,
        new java.lang.String[] { "OrderId", "Message", "LogAt", "OpType", });
    internal_static_com_alvin_logservice_lib_product_ProductLogReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alvin_logservice_lib_product_ProductLogReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alvin_logservice_lib_product_ProductLogReply_descriptor,
        new java.lang.String[] { "Done", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
