// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderLogService.proto

package com.alvin.logservice.lib.order;

public final class OrderLogServiceOuter {
  private OrderLogServiceOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alvin_logservice_lib_order_OrderLogRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alvin_logservice_lib_order_OrderLogRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alvin_logservice_lib_order_OrderLogReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alvin_logservice_lib_order_OrderLogReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025OrderLogService.proto\022\036com.alvin.logse" +
      "rvice.lib.order\"\307\001\n\017OrderLogRequest\022\017\n\007o" +
      "rderId\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\r\n\005logAt\030\003" +
      " \001(\003\022G\n\006opType\030\004 \001(\01627.com.alvin.logserv" +
      "ice.lib.order.OrderLogRequest.OPTypes\":\n" +
      "\007OPTypes\022\013\n\007CREATED\020\000\022\010\n\004EDIT\020\001\022\014\n\010TRANS" +
      "FER\020\002\022\n\n\006DELETE\020\003\"\035\n\rOrderLogReply\022\014\n\004do" +
      "ne\030\001 \001(\0102~\n\017OrderLogService\022k\n\007saveLog\022/" +
      ".com.alvin.logservice.lib.order.OrderLog" +
      "Request\032-.com.alvin.logservice.lib.order",
      ".OrderLogReply\"\000B8\n\036com.alvin.logservice" +
      ".lib.orderB\024OrderLogServiceOuterP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alvin_logservice_lib_order_OrderLogRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alvin_logservice_lib_order_OrderLogRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alvin_logservice_lib_order_OrderLogRequest_descriptor,
        new java.lang.String[] { "OrderId", "Message", "LogAt", "OpType", });
    internal_static_com_alvin_logservice_lib_order_OrderLogReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alvin_logservice_lib_order_OrderLogReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alvin_logservice_lib_order_OrderLogReply_descriptor,
        new java.lang.String[] { "Done", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
