// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderLogService.proto

package com.alvin.logservice.lib.order;

public interface OrderLogReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alvin.logservice.lib.order.OrderLogReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool done = 1;</code>
   */
  boolean getDone();
}
