spring:
  application:
    name: log-service
  data:
    mongodb:
      host: 192.168.254.14
      port: 27017
      username: admin
      password: admin
      database: 'log-service-db'
      authentication-database: 'admin'
server:
  port: 8080
grpc:
  port: 6565
  enable-reflection: true
  netty-server:
    keep-alive-time: 1000


eureka:
  instance:
    hostname: log-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka



