// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Address.proto

package com.alvin.logservice.lib.common;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.alvin.logservice.lib.common.Address)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string street1 = 2;</code>
   */
  java.lang.String getStreet1();
  /**
   * <code>string street1 = 2;</code>
   */
  com.google.protobuf.ByteString
      getStreet1Bytes();

  /**
   * <code>string street2 = 3;</code>
   */
  java.lang.String getStreet2();
  /**
   * <code>string street2 = 3;</code>
   */
  com.google.protobuf.ByteString
      getStreet2Bytes();

  /**
   * <code>string city = 4;</code>
   */
  java.lang.String getCity();
  /**
   * <code>string city = 4;</code>
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string state = 5;</code>
   */
  java.lang.String getState();
  /**
   * <code>string state = 5;</code>
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string zipcode = 6;</code>
   */
  java.lang.String getZipcode();
  /**
   * <code>string zipcode = 6;</code>
   */
  com.google.protobuf.ByteString
      getZipcodeBytes();

  /**
   * <code>string country = 7;</code>
   */
  java.lang.String getCountry();
  /**
   * <code>string country = 7;</code>
   */
  com.google.protobuf.ByteString
      getCountryBytes();
}
