// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.alvin.logservice.lib.common;

public final class UserOuter {
  private UserOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alvin_logservice_lib_common_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alvin_logservice_lib_common_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alvin_logservice_lib_common_User_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_alvin_logservice_lib_common_User_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022\037com.alvin.logservice.lib.c" +
      "ommon\"\247\001\n\004User\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t" +
      "\022\r\n\005email\030\003 \001(\t\032v\n\007Address\022\n\n\002id\030\001 \001(\t\022\017" +
      "\n\007street1\030\002 \001(\t\022\017\n\007street2\030\003 \001(\t\022\014\n\004city" +
      "\030\004 \001(\t\022\r\n\005state\030\005 \001(\t\022\017\n\007zipcode\030\006 \001(\t\022\017" +
      "\n\007country\030\007 \001(\tB.\n\037com.alvin.logservice." +
      "lib.commonB\tUserOuterP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alvin_logservice_lib_common_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alvin_logservice_lib_common_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alvin_logservice_lib_common_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
    internal_static_com_alvin_logservice_lib_common_User_Address_descriptor =
      internal_static_com_alvin_logservice_lib_common_User_descriptor.getNestedTypes().get(0);
    internal_static_com_alvin_logservice_lib_common_User_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_alvin_logservice_lib_common_User_Address_descriptor,
        new java.lang.String[] { "Id", "Street1", "Street2", "City", "State", "Zipcode", "Country", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
